import { prisma } from '@/lib/db';
export type CrmProspect={id:string;organizationName:string;contactName:string|null;email:string|null;phone:string|null;website:string|null;source:string|null;stage:string;owner:string|null;estimatedArrCents:number|null;nextAction:string|null;nextActionDate:Date|null;notes:string|null;createdAt:Date;updatedAt:Date};
let initialized=false;async function ensure(){if(initialized)return;await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS internal_crm_prospects (id TEXT PRIMARY KEY,organization_name TEXT NOT NULL,contact_name TEXT,email TEXT,phone TEXT,website TEXT,source TEXT,stage TEXT NOT NULL DEFAULT 'PROSPECT',owner TEXT,estimated_arr_cents INTEGER,next_action TEXT,next_action_date DATE,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS internal_crm_activity (id TEXT PRIMARY KEY,prospect_id TEXT NOT NULL,activity_type TEXT NOT NULL,note TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS internal_crm_stage_idx ON internal_crm_prospects(stage)`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS internal_crm_next_action_idx ON internal_crm_prospects(next_action_date)`);initialized=true}
function d(v:unknown){if(!v)return null;const x=v instanceof Date?v:new Date(String(v));return Number.isNaN(x.getTime())?null:x}function map(r:Record<string,unknown>):CrmProspect{return{id:String(r.id),organizationName:String(r.organization_name),contactName:r.contact_name?String(r.contact_name):null,email:r.email?String(r.email):null,phone:r.phone?String(r.phone):null,website:r.website?String(r.website):null,source:r.source?String(r.source):null,stage:String(r.stage),owner:r.owner?String(r.owner):null,estimatedArrCents:r.estimated_arr_cents==null?null:Number(r.estimated_arr_cents),nextAction:r.next_action?String(r.next_action):null,nextActionDate:d(r.next_action_date),notes:r.notes?String(r.notes):null,createdAt:d(r.created_at)??new Date(),updatedAt:d(r.updated_at)??new Date()}}
export async function listProspects(){await ensure();return(await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_crm_prospects ORDER BY updated_at DESC`)).map(map)}
export async function getProspect(id:string){await ensure();const r=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_crm_prospects WHERE id=$1 LIMIT 1`,id);return r[0]?map(r[0]):null}
export async function saveProspect(input:{id?:string;organizationName:string;contactName?:string|null;email?:string|null;phone?:string|null;website?:string|null;source?:string|null;stage?:string;owner?:string|null;estimatedArrCents?:number|null;nextAction?:string|null;nextActionDate?:string|null;notes?:string|null}){await ensure();const id=input.id||`crm_${crypto.randomUUID().replace(/-/g,'').slice(0,20)}`;const rows=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`INSERT INTO internal_crm_prospects (id,organization_name,contact_name,email,phone,website,source,stage,owner,estimated_arr_cents,next_action,next_action_date,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::date,$13) ON CONFLICT(id) DO UPDATE SET organization_name=EXCLUDED.organization_name,contact_name=EXCLUDED.contact_name,email=EXCLUDED.email,phone=EXCLUDED.phone,website=EXCLUDED.website,source=EXCLUDED.source,stage=EXCLUDED.stage,owner=EXCLUDED.owner,estimated_arr_cents=EXCLUDED.estimated_arr_cents,next_action=EXCLUDED.next_action,next_action_date=EXCLUDED.next_action_date,notes=EXCLUDED.notes,updated_at=NOW() RETURNING *`,id,input.organizationName,input.contactName||null,input.email||null,input.phone||null,input.website||null,input.source||null,input.stage||'PROSPECT',input.owner||null,input.estimatedArrCents??null,input.nextAction||null,input.nextActionDate||null,input.notes||null);return map(rows[0])}
export async function addCrmActivity(prospectId:string,activityType:string,note:string){await ensure();await prisma.$executeRawUnsafe(`INSERT INTO internal_crm_activity (id,prospect_id,activity_type,note) VALUES ($1,$2,$3,$4)`,`ca_${crypto.randomUUID().replace(/-/g,'').slice(0,20)}`,prospectId,activityType,note)}
export async function listCrmActivity(prospectId:string){await ensure();return prisma.$queryRawUnsafe<Array<{id:string;activity_type:string;note:string;created_at:Date}>>(`SELECT id,activity_type,note,created_at FROM internal_crm_activity WHERE prospect_id=$1 ORDER BY created_at DESC LIMIT 30`,prospectId)}
