import { prisma } from '@/lib/db';

export type OrderStatus = 'PENDING_SIGNATURE'|'SIGNED'|'PROVISIONING'|'READY_FOR_KICKOFF'|'IMPLEMENTATION'|'FULFILLED'|'VOIDED'|'FAILED';
export type OrderSource = 'TURBODOCX'|'STRIPE'|'MANUAL';
export type OnboardingTask = { id:string; label:string; description:string; completedAt:string|null };
export type InternalOrder = { id:string;orderNumber:string;source:OrderSource;status:OrderStatus;organizationName:string;ownerName:string|null;ownerEmail:string;subscriptionTier:'STARTER'|'GROWTH'|'ENTERPRISE';billingPeriod:string|null;arrCents:number|null;oneTimeCents:number|null;quoteId:string|null;turboSignDocumentId:string|null;stripeCheckoutSessionId:string|null;stripeSubscriptionId:string|null;organizationId:string|null;productsJson:string|null;notes:string|null;signedAt:Date|null;provisionedAt:Date|null;entitlementsProvisionedAt:Date|null;invitationSentAt:Date|null;activatedAt:Date|null;onboardingStartedAt:Date|null;onboardingTasksJson:string|null;fulfilledAt:Date|null;createdAt:Date;updatedAt:Date };
type CreateOrderInput={source:OrderSource;organizationName:string;ownerName?:string|null;ownerEmail:string;subscriptionTier:'STARTER'|'GROWTH'|'ENTERPRISE';billingPeriod?:string|null;arrCents?:number|null;oneTimeCents?:number|null;quoteId?:string|null;turboSignDocumentId?:string|null;stripeCheckoutSessionId?:string|null;stripeSubscriptionId?:string|null;products?:string[];notes?:string|null;status?:OrderStatus};
let initialized=false;
export async function ensureOrdersTable(){if(initialized)return;await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS internal_orders (id TEXT PRIMARY KEY,order_number TEXT NOT NULL UNIQUE,source TEXT NOT NULL,status TEXT NOT NULL,organization_name TEXT NOT NULL,owner_name TEXT,owner_email TEXT NOT NULL,subscription_tier TEXT NOT NULL,billing_period TEXT,arr_cents INTEGER,one_time_cents INTEGER,quote_id TEXT,turbosign_document_id TEXT UNIQUE,stripe_checkout_session_id TEXT UNIQUE,stripe_subscription_id TEXT,organization_id TEXT,products_json TEXT,notes TEXT,signed_at TIMESTAMPTZ,provisioned_at TIMESTAMPTZ,entitlements_provisioned_at TIMESTAMPTZ,invitation_sent_at TIMESTAMPTZ,activated_at TIMESTAMPTZ,onboarding_started_at TIMESTAMPTZ,onboarding_tasks_json TEXT,fulfilled_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);for(const sql of [`ALTER TABLE internal_orders ADD COLUMN IF NOT EXISTS entitlements_provisioned_at TIMESTAMPTZ`,`ALTER TABLE internal_orders ADD COLUMN IF NOT EXISTS invitation_sent_at TIMESTAMPTZ`,`ALTER TABLE internal_orders ADD COLUMN IF NOT EXISTS activated_at TIMESTAMPTZ`,`ALTER TABLE internal_orders ADD COLUMN IF NOT EXISTS onboarding_started_at TIMESTAMPTZ`,`ALTER TABLE internal_orders ADD COLUMN IF NOT EXISTS onboarding_tasks_json TEXT`,`ALTER TABLE internal_orders ADD COLUMN IF NOT EXISTS fulfilled_at TIMESTAMPTZ`,`CREATE INDEX IF NOT EXISTS internal_orders_status_idx ON internal_orders(status)`,`CREATE INDEX IF NOT EXISTS internal_orders_created_at_idx ON internal_orders(created_at DESC)`,`CREATE INDEX IF NOT EXISTS internal_orders_org_id_idx ON internal_orders(organization_id)`])await prisma.$executeRawUnsafe(sql);initialized=true}
function mapRow(r:Record<string,unknown>):InternalOrder{return{id:String(r.id),orderNumber:String(r.order_number),source:String(r.source) as OrderSource,status:String(r.status) as OrderStatus,organizationName:String(r.organization_name),ownerName:r.owner_name?String(r.owner_name):null,ownerEmail:String(r.owner_email),subscriptionTier:String(r.subscription_tier) as InternalOrder['subscriptionTier'],billingPeriod:r.billing_period?String(r.billing_period):null,arrCents:r.arr_cents==null?null:Number(r.arr_cents),oneTimeCents:r.one_time_cents==null?null:Number(r.one_time_cents),quoteId:r.quote_id?String(r.quote_id):null,turboSignDocumentId:r.turbosign_document_id?String(r.turbosign_document_id):null,stripeCheckoutSessionId:r.stripe_checkout_session_id?String(r.stripe_checkout_session_id):null,stripeSubscriptionId:r.stripe_subscription_id?String(r.stripe_subscription_id):null,organizationId:r.organization_id?String(r.organization_id):null,productsJson:r.products_json?String(r.products_json):null,notes:r.notes?String(r.notes):null,signedAt:r.signed_at?new Date(String(r.signed_at)):null,provisionedAt:r.provisioned_at?new Date(String(r.provisioned_at)):null,entitlementsProvisionedAt:r.entitlements_provisioned_at?new Date(String(r.entitlements_provisioned_at)):null,invitationSentAt:r.invitation_sent_at?new Date(String(r.invitation_sent_at)):null,activatedAt:r.activated_at?new Date(String(r.activated_at)):null,onboardingStartedAt:r.onboarding_started_at?new Date(String(r.onboarding_started_at)):null,onboardingTasksJson:r.onboarding_tasks_json?String(r.onboarding_tasks_json):null,fulfilledAt:r.fulfilled_at?new Date(String(r.fulfilled_at)):null,createdAt:new Date(String(r.created_at)),updatedAt:new Date(String(r.updated_at))}}
function newId(){return`ord_${crypto.randomUUID().replace(/-/g,'').slice(0,20)}`};async function nextOrderNumber(){const y=new Date().getFullYear();const rows=await prisma.$queryRawUnsafe<Array<{count:bigint|number}>>(`SELECT COUNT(*)::bigint AS count FROM internal_orders WHERE created_at >= $1 AND created_at < $2`,new Date(`${y}-01-01T00:00:00.000Z`),new Date(`${y+1}-01-01T00:00:00.000Z`));return`ORD-${y}-${String(Number(rows[0]?.count??0)+1).padStart(5,'0')}`}
export async function createOrder(i:CreateOrderInput){await ensureOrdersTable();const id=newId(),orderNumber=await nextOrderNumber(),pj=i.products?.length?JSON.stringify(i.products):null;const rows=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`INSERT INTO internal_orders (id,order_number,source,status,organization_name,owner_name,owner_email,subscription_tier,billing_period,arr_cents,one_time_cents,quote_id,turbosign_document_id,stripe_checkout_session_id,stripe_subscription_id,products_json,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,id,orderNumber,i.source,i.status??(i.source==='TURBODOCX'?'PENDING_SIGNATURE':'SIGNED'),i.organizationName,i.ownerName??null,i.ownerEmail.toLowerCase(),i.subscriptionTier,i.billingPeriod??null,i.arrCents??null,i.oneTimeCents??null,i.quoteId??null,i.turboSignDocumentId??null,i.stripeCheckoutSessionId??null,i.stripeSubscriptionId??null,pj,i.notes??null);return mapRow(rows[0])}
export async function listOrders(){await ensureOrdersTable();return(await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_orders ORDER BY created_at DESC LIMIT 250`)).map(mapRow)}
export async function getOrder(id:string){await ensureOrdersTable();const r=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_orders WHERE id=$1 LIMIT 1`,id);return r[0]?mapRow(r[0]):null}
export async function getOrderByOrganizationId(id:string){await ensureOrdersTable();const r=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_orders WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 1`,id);return r[0]?mapRow(r[0]):null}
export async function getOrderByTurboSignDocumentId(id:string){await ensureOrdersTable();const r=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_orders WHERE turbosign_document_id=$1 LIMIT 1`,id);return r[0]?mapRow(r[0]):null}
export async function getOrderByStripeSessionId(id:string){await ensureOrdersTable();const r=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_orders WHERE stripe_checkout_session_id=$1 LIMIT 1`,id);return r[0]?mapRow(r[0]):null}
export async function findPendingTurboDocxOrders(){await ensureOrdersTable();return(await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_orders WHERE source='TURBODOCX' AND status='PENDING_SIGNATURE' ORDER BY created_at DESC LIMIT 100`)).map(mapRow)}
function norm(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
export async function findPendingTurboDocxOrderByDocumentTitle(title:string){const t=norm(title);if(!t)return null;const m=(await findPendingTurboDocxOrders()).filter(o=>(norm(o.organizationName).length>1&&t.includes(norm(o.organizationName)))||(o.quoteId&&norm(o.quoteId).length>1&&t.includes(norm(o.quoteId))));return m.length===1?m[0]:null}
export function defaultOnboardingTasks(activatedAt:Date|null=new Date()):OnboardingTask[]{return[{id:'account',label:'Account activated',description:'Owner accepts the invitation and activates the Donor Success workspace.',completedAt:activatedAt?.toISOString()??null},{id:'kickoff',label:'Kickoff completed',description:'Confirm goals, timeline, team roles, and launch plan.',completedAt:null},{id:'data',label:'Donor data loaded',description:'Import or connect the initial donor file and validate records.',completedAt:null},{id:'team',label:'Team access configured',description:'Invite the working team and confirm permissions.',completedAt:null},{id:'journey',label:'First donor journey configured',description:'Configure the first journey, playbook, or engagement workflow.',completedAt:null},{id:'launch',label:'Launch review complete',description:'Review readiness, reporting, and next-30-day success plan.',completedAt:null}]}
export function parseOnboardingTasks(o:InternalOrder):OnboardingTask[]{if(!o.onboardingTasksJson)return[];try{return JSON.parse(o.onboardingTasksJson)}catch{return[]}}
export async function activateOrderOnboardingByOrganizationId(orgId:string){const o=await getOrderByOrganizationId(orgId);if(!o||o.status==='VOIDED')return null;const now=new Date(),tasks=parseOnboardingTasks(o),next=tasks.length?tasks.map(t=>t.id==='account'&&!t.completedAt?{...t,completedAt:now.toISOString()}:t):defaultOnboardingTasks(now);return updateOrder(o.id,{status:o.status==='FULFILLED'?'FULFILLED':'IMPLEMENTATION',activatedAt:o.activatedAt??now,onboardingStartedAt:o.onboardingStartedAt??now,onboardingTasksJson:JSON.stringify(next)})}
export async function updateOnboardingTask(orderId:string,taskId:string,completed:boolean){const o=await getOrder(orderId);if(!o)return null;let tasks=parseOnboardingTasks(o);if(!tasks.length)tasks=defaultOnboardingTasks(o.activatedAt);const now=new Date().toISOString(),next=tasks.map(t=>t.id===taskId?{...t,completedAt:completed?(t.completedAt??now):null}:t),all=next.every(t=>!!t.completedAt);return updateOrder(orderId,{onboardingTasksJson:JSON.stringify(next),status:all?'FULFILLED':'IMPLEMENTATION',fulfilledAt:all?(o.fulfilledAt??new Date()):null})}
export async function updateOrder(id:string,c:Partial<Pick<InternalOrder,'status'|'organizationId'|'signedAt'|'provisionedAt'|'notes'|'stripeSubscriptionId'|'turboSignDocumentId'|'entitlementsProvisionedAt'|'invitationSentAt'|'activatedAt'|'onboardingStartedAt'|'onboardingTasksJson'|'fulfilledAt'>>){await ensureOrdersTable();const o=await getOrder(id);if(!o)return null;const r=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`UPDATE internal_orders SET status=$2,organization_id=$3,signed_at=$4,provisioned_at=$5,notes=$6,stripe_subscription_id=$7,turbosign_document_id=$8,entitlements_provisioned_at=$9,invitation_sent_at=$10,activated_at=$11,onboarding_started_at=$12,onboarding_tasks_json=$13,fulfilled_at=$14,updated_at=NOW() WHERE id=$1 RETURNING *`,id,c.status??o.status,c.organizationId??o.organizationId,c.signedAt??o.signedAt,c.provisionedAt??o.provisionedAt,c.notes??o.notes,c.stripeSubscriptionId??o.stripeSubscriptionId,c.turboSignDocumentId??o.turboSignDocumentId,c.entitlementsProvisionedAt??o.entitlementsProvisionedAt,c.invitationSentAt??o.invitationSentAt,c.activatedAt??o.activatedAt,c.onboardingStartedAt??o.onboardingStartedAt,c.onboardingTasksJson??o.onboardingTasksJson,Object.prototype.hasOwnProperty.call(c,'fulfilledAt')?c.fulfilledAt:o.fulfilledAt);return r[0]?mapRow(r[0]):null}
