import { prisma } from '@/lib/db';

export type RenewalExecution = { organizationId:string; forecastPercent:number|null; nextAction:string|null; nextActionDate:Date|null; riskReason:string|null; completedSteps:string[]; updatedAt:Date };
let initialized=false;
async function ensure(){if(initialized)return;await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS internal_renewal_execution (organization_id TEXT PRIMARY KEY,forecast_percent INTEGER,next_action TEXT,next_action_date DATE,risk_reason TEXT,completed_steps_json TEXT NOT NULL DEFAULT '[]',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS internal_renewal_activity (id TEXT PRIMARY KEY,organization_id TEXT NOT NULL,activity_type TEXT NOT NULL,note TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await prisma.$executeRawUnsafe(`CREATE INDEX IF NOT EXISTS internal_renewal_activity_org_idx ON internal_renewal_activity(organization_id,created_at DESC)`);initialized=true}
function parseDate(v:unknown){if(!v)return null;const d=v instanceof Date?v:new Date(String(v));return Number.isNaN(d.getTime())?null:d}
function map(r:Record<string,unknown>):RenewalExecution{return{organizationId:String(r.organization_id),forecastPercent:r.forecast_percent==null?null:Number(r.forecast_percent),nextAction:r.next_action?String(r.next_action):null,nextActionDate:parseDate(r.next_action_date),riskReason:r.risk_reason?String(r.risk_reason):null,completedSteps:r.completed_steps_json?JSON.parse(String(r.completed_steps_json)):[],updatedAt:parseDate(r.updated_at)??new Date()}}
export async function listRenewalExecution(){await ensure();return(await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`SELECT * FROM internal_renewal_execution`)).map(map)}
export async function saveRenewalExecution(input:{organizationId:string;forecastPercent:number|null;nextAction:string|null;nextActionDate:string|null;riskReason:string|null;completedSteps:string[]}){await ensure();const rows=await prisma.$queryRawUnsafe<Record<string,unknown>[]>(`INSERT INTO internal_renewal_execution (organization_id,forecast_percent,next_action,next_action_date,risk_reason,completed_steps_json) VALUES ($1,$2,$3,$4::date,$5,$6) ON CONFLICT (organization_id) DO UPDATE SET forecast_percent=EXCLUDED.forecast_percent,next_action=EXCLUDED.next_action,next_action_date=EXCLUDED.next_action_date,risk_reason=EXCLUDED.risk_reason,completed_steps_json=EXCLUDED.completed_steps_json,updated_at=NOW() RETURNING *`,input.organizationId,input.forecastPercent,input.nextAction,input.nextActionDate,input.riskReason,JSON.stringify(input.completedSteps));return map(rows[0])}
export async function addRenewalActivity(organizationId:string,activityType:string,note:string){await ensure();await prisma.$executeRawUnsafe(`INSERT INTO internal_renewal_activity (id,organization_id,activity_type,note) VALUES ($1,$2,$3,$4)`,`ra_${crypto.randomUUID().replace(/-/g,'').slice(0,20)}`,organizationId,activityType,note)}
export async function listRenewalActivity(organizationId:string){await ensure();return prisma.$queryRawUnsafe<Array<{id:string;activity_type:string;note:string;created_at:Date}>>(`SELECT id,activity_type,note,created_at FROM internal_renewal_activity WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 20`,organizationId)}
