import Link from 'next/link';
import { prisma } from '@/lib/db';
import { listCustomerLifecycleRecords, daysToRenewal } from '@/lib/customer-lifecycle';
import { renewalStage, stageLabel, playbookFor, renewalRisk } from '@/lib/renewal-playbook';
import { AlertTriangle, CalendarClock, CheckCircle2, Target } from 'lucide-react';

export default async function RenewalPipelinePage(){
 const [orgs,lifecycle]=await Promise.all([prisma.organization.findMany({include:{users:{select:{lastLoginAt:true,isActive:true}},donors:{select:{healthScore:true}}}}),listCustomerLifecycleRecords()]);
 const byOrg=new Map(lifecycle.map(x=>[x.organizationId,x]));
 const rows=orgs.map(o=>{const r=byOrg.get(o.id)??null;const logins=o.users.filter(u=>u.isActive&&u.lastLoginAt).map(u=>u.lastLoginAt!).sort((a,b)=>b.getTime()-a.getTime());const scores=o.donors.map(d=>d.healthScore).filter((x):x is number=>x!=null);const avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null;const stage=renewalStage(r),risk=renewalRisk(r,logins[0]??null,avg);return{o,r,stage,risk,days:r?.renewalDate?daysToRenewal(r.renewalDate):null,steps:playbookFor(r)}}).sort((a,b)=>(a.days??99999)-(b.days??99999));
 const active=rows.filter(x=>x.stage!=='NO_DATE'&&x.stage!=='RENEWED'),atRisk=rows.filter(x=>x.risk.atRisk&&x.stage!=='RENEWED'),committed=rows.filter(x=>x.r?.renewalStatus==='COMMITTED'),renewed=rows.filter(x=>x.stage==='RENEWED');
 return <div className="space-y-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal">Renewal Playbook</p><h1 className="mt-2 text-3xl font-extrabold text-white">Renewal Pipeline</h1><p className="mt-1 text-sm text-gray-400">180-day renewal motion with stage-based actions, risk signals and close visibility.</p></div><Link href="/admin/customers" className="rounded-xl border border-gray-700 px-4 py-2.5 text-sm font-bold text-white">Customer Success Command Center</Link></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CalendarClock size={18}/>} label="Active Renewals" value={active.length}/><Metric icon={<AlertTriangle size={18}/>} label="At Risk" value={atRisk.length}/><Metric icon={<Target size={18}/>} label="Committed" value={committed.length}/><Metric icon={<CheckCircle2 size={18}/>} label="Renewed" value={renewed.length}/></div>
 <section className="rounded-2xl border border-gray-800 bg-gray-800/40 p-5"><h2 className="font-extrabold text-white">Renewal Stage Board</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.filter(x=>x.stage!=='NO_DATE').map(x=><details key={x.o.id} className={`rounded-xl border p-4 ${x.risk.atRisk?'border-red-500/30 bg-red-500/5':'border-gray-700 bg-gray-900/30'}`}><summary className="cursor-pointer list-none"><div className="flex justify-between gap-3"><div><div className="font-bold text-white">{x.o.name}</div><div className="mt-1 text-xs text-gray-500">{stageLabel(x.stage)} · {x.r?.renewalOwner||'No owner'}</div></div><div className="text-right"><div className={`text-sm font-black ${x.days!=null&&x.days<=60?'text-amber-300':'text-teal'}`}>{x.stage==='RENEWED'?'✓':x.days!=null?`${x.days}d`:'—'}</div><div className="text-[10px] uppercase text-gray-600">{x.r?.renewalStatus.replaceAll('_',' ')}</div></div></div>{x.risk.atRisk&&<div className="mt-3 rounded-lg bg-red-500/10 p-2 text-xs text-red-200">{x.risk.reasons.join(' · ')}</div>}</summary><div className="mt-4 border-t border-gray-700 pt-4"><div className="text-xs font-bold uppercase text-gray-500">Playbook</div><div className="mt-3 space-y-3">{x.steps.map(s=><div key={s.id} className="flex gap-3"><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs ${s.complete?'bg-emerald-500/20 text-emerald-300':'bg-gray-700 text-gray-400'}`}>{s.complete?'✓':'·'}</span><div><div className="text-sm font-bold text-gray-200">{s.label}</div><div className="text-xs leading-5 text-gray-500">{s.description}</div><div className="mt-1 text-[10px] font-bold uppercase text-teal">{stageLabel(s.dueStage)}</div></div></div>)}</div><Link href="/admin/customers" className="mt-4 inline-block text-xs font-bold text-teal">Update renewal details →</Link></div></details>)}</div></section>
 {rows.some(x=>x.stage==='NO_DATE')&&<section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><h2 className="font-extrabold text-amber-200">Renewal Dates Needed</h2><p className="mt-1 text-xs text-gray-500">These customers cannot enter the automated playbook until a contractual renewal date is set.</p><div className="mt-4 flex flex-wrap gap-2">{rows.filter(x=>x.stage==='NO_DATE').map(x=><Link key={x.o.id} href="/admin/customers" className="rounded-lg border border-gray-700 bg-gray-900/40 px-3 py-2 text-sm font-semibold text-white">{x.o.name}</Link>)}</div></section>}</div>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-2xl border border-gray-800 bg-gray-800/40 p-4"><div className="flex items-center gap-2 text-teal">{icon}<span className="text-xs font-bold uppercase text-gray-500">{label}</span></div><div className="mt-3 text-2xl font-black text-white">{value}</div></div>}
