import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getOrder, parseOnboardingTasks, defaultOnboardingTasks } from '@/lib/orders';
import { provisionOrderAction, retryOwnerInvitationAction, toggleOnboardingTaskAction } from '@/lib/actions/orders';
import OrderActivityTimeline from '@/components/admin/OrderActivityTimeline';

function money(cents: number | null) { if (cents == null) return '—'; return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100); }
function when(value: Date | null) { return value ? value.toLocaleString() : 'Pending'; }

export default async function OrderDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams?: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const messages = searchParams ? await searchParams : {}; const order = await getOrder(id); if (!order) notFound();
  const products = order.productsJson ? (JSON.parse(order.productsJson) as string[]) : [];
  const storedTasks = parseOnboardingTasks(order);
  const onboardingTasks = storedTasks.length ? storedTasks : defaultOnboardingTasks(null);
  const onboardingDone = onboardingTasks.filter((t) => t.completedAt).length;
  const onboardingProgress = Math.round((onboardingDone / onboardingTasks.length) * 100);
  const canProvision = ['SIGNED', 'FAILED'].includes(order.status) && !order.organizationId;
  const needsInvitationRetry = Boolean(order.organizationId) && !order.invitationSentAt;
  const showOnboarding = Boolean(order.organizationId);
  const completedSteps = [order.signedAt, order.organizationId, order.entitlementsProvisionedAt, order.invitationSentAt, order.activatedAt, order.fulfilledAt].filter(Boolean).length;
  const progress = Math.round((completedSteps / 6) * 100);
  const nextAction = canProvision ? 'The agreement is signed. Provision the customer workspace and invite the owner.' : needsInvitationRetry ? `The customer workspace exists, but the owner invitation has not been confirmed as sent. Retry the invitation to ${order.ownerEmail}.` : !order.activatedAt ? 'Workspace is provisioned. Waiting for the customer to activate their account.' : order.status === 'IMPLEMENTATION' ? `Onboarding is active. ${onboardingDone} of ${onboardingTasks.length} launch tasks are complete.` : order.status === 'FULFILLED' ? 'Customer launch is complete and the order is fulfilled.' : 'Waiting for the next lifecycle milestone.';

  return <div className="space-y-7">
    <div className="flex items-start justify-between gap-4"><div><Link href="/admin/orders" className="text-sm font-semibold text-gray-400 hover:text-white">← Orders & Fulfillment</Link><div className="mt-3 flex items-center gap-3"><h1 className="text-3xl font-extrabold text-white">{order.orderNumber}</h1><span className="rounded-full bg-evergreen/20 px-3 py-1 text-xs font-bold text-teal">{order.status.replaceAll('_', ' ')}</span></div><p className="mt-2 text-gray-400">{order.organizationName} · {order.ownerEmail}</p></div>{order.organizationId && <Link href={`/admin/organizations/${order.organizationId}`} className="rounded-xl bg-evergreen px-4 py-2.5 text-sm font-bold text-white">View customer account</Link>}</div>
    {messages.error && <div className="rounded-2xl border border-red-500/30 bg-red-500/10 px-5 py-4 text-sm text-red-200"><b>Fulfillment action needs attention</b><div className="mt-1">{messages.error}</div></div>}
    {messages.success && <div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 px-5 py-4 text-sm text-emerald-200">{messages.success}</div>}
    <section className="rounded-2xl border border-gray-800 bg-gradient-to-r from-gray-800/70 to-gray-900 p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-warning">Fulfillment Command Center</p><h2 className="mt-2 text-xl font-extrabold text-white">{order.organizationName} launch readiness</h2><p className="mt-1 text-sm text-gray-400">Signed agreement → activation → onboarding → live.</p></div><div className="min-w-44"><div className="flex justify-between text-xs font-bold text-gray-400"><span>Lifecycle</span><span>{progress}%</span></div><div className="mt-2 h-2 rounded-full bg-gray-700"><div className="h-full rounded-full bg-teal" style={{width:`${progress}%`}} /></div></div></div></section>
    <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-gray-800 bg-gray-800/40 p-5 lg:col-span-2"><h2 className="font-bold text-white">Commercial summary</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Plan" value={order.subscriptionTier}/><Field label="Billing" value={order.billingPeriod ?? '—'}/><Field label="ARR" value={money(order.arrCents)}/><Field label="One-time" value={money(order.oneTimeCents)}/><Field label="TurboQuote" value={order.quoteId ?? '—'}/><Field label="TurboSign document" value={order.turboSignDocumentId ?? 'Auto-link pending'}/></div><div className="mt-5 border-t border-gray-800 pt-5"><div className="text-xs font-bold uppercase text-gray-500">Provisioned products / modules</div><div className="mt-2 flex flex-wrap gap-2">{products.map(p=><span key={p} className="rounded-full bg-teal/10 px-3 py-1 text-xs font-semibold text-teal">✓ {p}</span>)}</div></div></section><section className="rounded-2xl border border-gray-800 bg-gray-800/40 p-5"><h2 className="font-bold text-white">Next action</h2><p className="mt-2 text-sm leading-6 text-gray-400">{nextAction}</p>{canProvision&&<form action={provisionOrderAction} className="mt-6"><input type="hidden" name="orderId" value={order.id}/><button className="w-full rounded-xl bg-evergreen px-4 py-3 text-sm font-bold text-white">Provision Customer</button></form>}{needsInvitationRetry&&<form action={retryOwnerInvitationAction} className="mt-6"><input type="hidden" name="orderId" value={order.id}/><button className="w-full rounded-xl bg-amber-500 px-4 py-3 text-sm font-bold text-gray-950">Retry Owner Invitation</button></form>}</section></div>
    <section className="rounded-2xl border border-gray-800 bg-gray-800/40 p-6"><h2 className="font-bold text-white">Fulfillment checklist</h2><div className="mt-5 grid gap-3 md:grid-cols-2"><Milestone label="Contract signed" done={!!order.signedAt} detail={when(order.signedAt)}/><Milestone label="Organization created" done={!!order.organizationId} detail={order.organizationId?'Customer workspace active':'Pending provisioning'}/><Milestone label={`${order.subscriptionTier} + product entitlements`} done={!!order.entitlementsProvisionedAt} detail={when(order.entitlementsProvisionedAt)}/><Milestone label="Owner / admin invitation" done={!!order.invitationSentAt} detail={order.invitationSentAt?`Sent to ${order.ownerEmail}`:'Pending'}/><Milestone label="Customer account activated" done={!!order.activatedAt} detail={when(order.activatedAt)}/><Milestone label="Fulfillment complete" done={!!order.fulfilledAt} detail={when(order.fulfilledAt)}/></div></section>
    {showOnboarding && <section className="rounded-2xl border border-teal/20 bg-gray-800/50 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal">Onboarding Workspace</p><h2 className="mt-2 text-xl font-extrabold text-white">30-Day Launch Checklist</h2><p className="mt-1 text-sm text-gray-400">Visible from provisioning. Account activation automatically starts implementation.</p></div><div className="min-w-44"><div className="flex justify-between text-xs font-bold text-gray-400"><span>Onboarding</span><span>{onboardingProgress}%</span></div><div className="mt-2 h-2 rounded-full bg-gray-700"><div className="h-full bg-teal" style={{width:`${onboardingProgress}%`}}/></div></div></div><div className="mt-6 grid gap-3 md:grid-cols-2">{onboardingTasks.map(task=><div key={task.id} className={`rounded-xl border p-4 ${task.completedAt?'border-emerald-500/20 bg-emerald-500/5':'border-gray-700 bg-gray-900/30'}`}><div className="flex gap-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${task.completedAt?'bg-emerald-500/20 text-emerald-400':'bg-gray-700 text-gray-500'}`}>{task.completedAt?'✓':'·'}</span><div className="flex-1"><div className="font-bold text-gray-100">{task.label}</div><p className="mt-1 text-xs leading-5 text-gray-500">{task.description}</p><div className="mt-3 flex items-center justify-between"><span className="text-[11px] text-gray-500">{task.id==='account'&&!order.activatedAt?'Waiting on customer':task.completedAt?new Date(task.completedAt).toLocaleString():'Open'}</span>{order.activatedAt&&task.id!=='account'&&<form action={toggleOnboardingTaskAction}><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="completed" value={task.completedAt?'false':'true'}/><button className="rounded-lg border border-gray-700 px-3 py-1.5 text-xs font-bold text-gray-200">{task.completedAt?'Reopen':'Complete'}</button></form>}</div></div></div></div>)}</div></section>}
    <OrderActivityTimeline notes={order.notes} signedAt={order.signedAt} provisionedAt={order.provisionedAt} invitationSentAt={order.invitationSentAt} activatedAt={order.activatedAt} onboardingStartedAt={order.onboardingStartedAt} fulfilledAt={order.fulfilledAt}/>
  </div>;
}
function Field({label,value}:{label:string;value:string}){return <div><div className="text-xs font-bold uppercase text-gray-500">{label}</div><div className="mt-1 break-words text-sm font-semibold text-gray-100">{value}</div></div>}
function Milestone({label,done,detail}:{label:string;done:boolean;detail:string}){return <div className={`rounded-xl border p-4 ${done?'border-emerald-500/20 bg-emerald-500/5':'border-gray-700 bg-gray-900/30'}`}><div className="flex gap-3"><span className={`flex h-7 w-7 items-center justify-center rounded-full ${done?'bg-emerald-500/20 text-emerald-400':'bg-gray-700 text-gray-500'}`}>{done?'✓':'·'}</span><div><div className="text-sm font-bold text-gray-200">{label}</div><div className="mt-1 text-xs text-gray-500">{detail}</div></div></div></div>}
