import Link from 'next/link';
import { prisma } from '@/lib/db';
import { listOrders } from '@/lib/orders';
import { Activity, AlertTriangle, Building2, CalendarClock, HeartPulse, Users } from 'lucide-react';

function daysSince(d: Date | null) { return d ? Math.floor((Date.now()-d.getTime())/86400000) : null; }
function healthLabel(score:number|null, activeUsers:number, donorCount:number, lastLogin:Date|null, status:string|null){
  const idle=daysSince(lastLogin); if(status&&['past_due','canceled','unpaid'].includes(status)) return {label:'At Risk',tone:'red'};
  if(score!=null&&score<60)return{label:'At Risk',tone:'red'}; if(idle!=null&&idle>30)return{label:'Watch',tone:'amber'};
  if(activeUsers===0)return{label:'Activation',tone:'amber'}; if(donorCount===0)return{label:'Setup',tone:'amber'}; return{label:'Healthy',tone:'green'};
}
export default async function CustomerLifecyclePage(){
  const [orgs,orders]=await Promise.all([prisma.organization.findMany({orderBy:{createdAt:'desc'},include:{users:{select:{lastLoginAt:true,isActive:true}},donors:{select:{healthScore:true}}}}),listOrders()]);
  const orderByOrg=new Map(orders.filter(o=>o.organizationId).map(o=>[o.organizationId!,o]));
  const rows=orgs.map(o=>{const active=o.users.filter(u=>u.isActive),lastLogin=active.map(u=>u.lastLoginAt).filter(Boolean).sort((a,b)=>b!.getTime()-a!.getTime())[0]??null;const scores=o.donors.map(d=>d.healthScore).filter((x):x is number=>x!=null);const avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null;const health=healthLabel(avg,active.length,o.donors.length,lastLogin,o.subscriptionStatus);return{o,activeUsers:active.length,lastLogin,avg,health,order:orderByOrg.get(o.id)}});
  const healthy=rows.filter(r=>r.health.label==='Healthy').length, risk=rows.filter(r=>r.health.label==='At Risk').length, watch=rows.filter(r=>['Watch','Activation','Setup'].includes(r.health.label)).length;
  return <div className="space-y-7"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal">Customer Lifecycle</p><h1 className="mt-2 text-3xl font-extrabold text-white">Customer Success Command Center</h1><p className="mt-1 text-sm text-gray-400">Post-sale visibility across activation, adoption, health and subscription status.</p></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Building2 size={18}/>} label="Customers" value={rows.length}/><Metric icon={<HeartPulse size={18}/>} label="Healthy" value={healthy}/><Metric icon={<AlertTriangle size={18}/>} label="Needs Attention" value={risk+watch}/><Metric icon={<Activity size={18}/>} label="In Onboarding" value={rows.filter(r=>['READY_FOR_KICKOFF','IMPLEMENTATION'].includes(r.order?.status??'')).length}/></div>
  <section className="rounded-2xl border border-gray-800 bg-gray-800/40 p-5"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-white">Customer Portfolio</h2><p className="mt-1 text-xs text-gray-500">Health is an operational signal using donor health, activation, usage and billing state—not a replacement for donor-level health scoring.</p></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr className="border-b border-gray-800 text-xs uppercase text-gray-500"><th className="py-3">Customer</th><th>Lifecycle</th><th>Health</th><th>Users</th><th>Donors</th><th>Avg donor health</th><th>Last login</th><th>Subscription</th></tr></thead><tbody>{rows.map(r=><tr key={r.o.id} className="border-b border-gray-800 last:border-0"><td className="py-4"><Link href={`/admin/organizations/${r.o.id}`} className="font-bold text-white hover:text-teal">{r.o.name}</Link><div className="text-xs text-gray-600">{r.o.subscriptionTier}</div></td><td><span className="text-xs font-semibold text-gray-300">{r.order?.status.replaceAll('_',' ')??'ACTIVE'}</span></td><td><Health label={r.health.label} tone={r.health.tone}/></td><td className="text-gray-300">{r.activeUsers}</td><td className="text-gray-300">{r.o.donors.length}</td><td className="text-gray-300">{r.avg??'—'}</td><td className="text-gray-400">{r.lastLogin?r.lastLogin.toLocaleDateString():'Never'}</td><td><span className="text-xs font-semibold text-gray-300">{r.o.subscriptionStatus??'—'}</span></td></tr>)}</tbody></table></div></section>
  <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><div className="flex items-center gap-2 text-amber-300"><AlertTriangle size={18}/><h2 className="font-extrabold">Customer Attention Queue</h2></div><div className="mt-4 space-y-2">{rows.filter(r=>r.health.label!=='Healthy').slice(0,8).map(r=><Link key={r.o.id} href={`/admin/organizations/${r.o.id}`} className="flex justify-between rounded-xl border border-gray-700 bg-gray-900/30 p-3"><div><div className="font-bold text-white">{r.o.name}</div><div className="text-xs text-gray-500">{r.health.label} · {r.lastLogin?`${daysSince(r.lastLogin)} days since login`:'No customer login yet'}</div></div><span className="text-xs font-bold text-amber-300">Review →</span></Link>)}{rows.every(r=>r.health.label==='Healthy')&&<p className="text-sm text-gray-400">No customers currently require attention.</p>}</div></section>
  <section className="rounded-2xl border border-gray-800 bg-gray-800/40 p-5"><div className="flex items-center gap-2 text-teal"><CalendarClock size={18}/><h2 className="font-extrabold text-white">Lifecycle Controls</h2></div><div className="mt-4 space-y-3"><Link href="/admin/orders" className="block rounded-xl border border-gray-700 p-4"><b className="text-white">Fulfillment & Onboarding</b><p className="mt-1 text-xs text-gray-500">Manage signed orders, provisioning, activation and launch.</p></Link><Link href="/admin" className="block rounded-xl border border-gray-700 p-4"><b className="text-white">Platform Command Center</b><p className="mt-1 text-xs text-gray-500">Return to customer, platform and operating metrics.</p></Link></div></section></div></div>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number|string}){return <div className="rounded-2xl border border-gray-800 bg-gray-800/40 p-4"><div className="flex items-center gap-2 text-teal">{icon}<span className="text-xs font-bold uppercase text-gray-500">{label}</span></div><div className="mt-3 text-2xl font-black text-white">{value}</div></div>}
function Health({label,tone}:{label:string;tone:string}){const c=tone==='green'?'bg-emerald-500/10 text-emerald-300':tone==='red'?'bg-red-500/10 text-red-300':'bg-amber-500/10 text-amber-300';return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${c}`}>{label}</span>}
