import Link from 'next/link';
import { prisma } from '@/lib/db';
import { listOrders } from '@/lib/orders';
import { listCustomerLifecycleRecords, daysToRenewal } from '@/lib/customer-lifecycle';
import { saveCustomerRenewalAction } from '@/lib/actions/customer-lifecycle';
import { Activity, AlertTriangle, Building2, CalendarClock, HeartPulse } from 'lucide-react';

function daysSince(d: Date | null) { return d ? Math.floor((Date.now()-d.getTime())/86400000) : null; }
function healthLabel(score:number|null, activeUsers:number, donorCount:number, lastLogin:Date|null, status:string|null){
  const idle=daysSince(lastLogin); if(status&&['past_due','canceled','unpaid'].includes(status)) return {label:'At Risk',tone:'red'};
  if(score!=null&&score<60)return{label:'At Risk',tone:'red'}; if(idle!=null&&idle>30)return{label:'Watch',tone:'amber'};
  if(activeUsers===0)return{label:'Activation',tone:'amber'}; if(donorCount===0)return{label:'Setup',tone:'amber'}; return{label:'Healthy',tone:'green'};
}
function renewalTone(days:number|null,status:string){if(status==='AT_RISK'||(days!=null&&days<0))return'red';if(days!=null&&days<=90)return'amber';return'green'}
function renewalText(days:number|null){if(days==null)return'Not set';if(days<0)return`${Math.abs(days)}d overdue`;if(days===0)return'Today';return`${days}d`}

export default async function CustomerLifecyclePage({searchParams}:{searchParams?:Promise<{success?:string;error?:string}>}){
  const messages=searchParams?await searchParams:{};
  const [orgs,orders,lifecycle]=await Promise.all([
    prisma.organization.findMany({orderBy:{createdAt:'desc'},include:{users:{select:{lastLoginAt:true,isActive:true}},donors:{select:{healthScore:true}}}}),
    listOrders(), listCustomerLifecycleRecords()
  ]);
  const orderByOrg=new Map(orders.filter(o=>o.organizationId).map(o=>[o.organizationId!,o]));
  const lifecycleByOrg=new Map(lifecycle.map(x=>[x.organizationId,x]));
  const rows=orgs.map(o=>{const active=o.users.filter(u=>u.isActive),lastLogin=active.map(u=>u.lastLoginAt).filter(Boolean).sort((a,b)=>b!.getTime()-a!.getTime())[0]??null;const scores=o.donors.map(d=>d.healthScore).filter((x):x is number=>x!=null);const avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):null;const health=healthLabel(avg,active.length,o.donors.length,lastLogin,o.subscriptionStatus);const renewal=lifecycleByOrg.get(o.id)??null;const renewalDays=daysToRenewal(renewal?.renewalDate??null);return{o,activeUsers:active.length,lastLogin,avg,health,order:orderByOrg.get(o.id),renewal,renewalDays}});
  const healthy=rows.filter(r=>r.health.label==='Healthy').length, risk=rows.filter(r=>r.health.label==='At Risk').length, watch=rows.filter(r=>['Watch','Activation','Setup'].includes(r.health.label)).length;
  const upcoming=rows.filter(r=>r.renewalDays!=null&&r.renewalDays>=0&&r.renewalDays<=120).sort((a,b)=>(a.renewalDays??9999)-(b.renewalDays??9999));
  const missingRenewal=rows.filter(r=>!r.renewal?.renewalDate).length;

  return <div className="space-y-7"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal">Customer Lifecycle</p><h1 className="mt-2 text-3xl font-extrabold text-white">Customer Success Command Center</h1><p className="mt-1 text-sm text-gray-400">Post-sale visibility across activation, adoption, health, subscription and renewal readiness.</p></div>
  {messages.success&&<div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-200">{messages.success}</div>}{messages.error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{messages.error}</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={<Building2 size={18}/>} label="Customers" value={rows.length}/><Metric icon={<HeartPulse size={18}/>} label="Healthy" value={healthy}/><Metric icon={<AlertTriangle size={18}/>} label="Needs Attention" value={risk+watch}/><Metric icon={<Activity size={18}/>} label="In Onboarding" value={rows.filter(r=>['READY_FOR_KICKOFF','IMPLEMENTATION'].includes(r.order?.status??'')).length}/><Metric icon={<CalendarClock size={18}/>} label="Renewal Dates Missing" value={missingRenewal}/></div>

  <section className="rounded-2xl border border-gray-800 bg-gray-800/40 p-5"><div><h2 className="font-extrabold text-white">Customer Portfolio</h2><p className="mt-1 text-xs text-gray-500">Renewal dates are explicit contract dates entered by an admin; the system does not infer them from signup or billing dates.</p></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1150px] text-left text-sm"><thead><tr className="border-b border-gray-800 text-xs uppercase text-gray-500"><th className="py-3">Customer</th><th>Lifecycle</th><th>Health</th><th>Users</th><th>Donors</th><th>Avg donor health</th><th>Last login</th><th>Renewal</th><th>Renewal Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.o.id} className="border-b border-gray-800 last:border-0"><td className="py-4"><Link href={`/admin/organizations/${r.o.id}`} className="font-bold text-white hover:text-teal">{r.o.name}</Link><div className="text-xs text-gray-600">{r.o.subscriptionTier}</div></td><td><span className="text-xs font-semibold text-gray-300">{r.order?.status.replaceAll('_',' ')??'ACTIVE'}</span></td><td><Health label={r.health.label} tone={r.health.tone}/></td><td className="text-gray-300">{r.activeUsers}</td><td className="text-gray-300">{r.o.donors.length}</td><td className="text-gray-300">{r.avg??'—'}</td><td className="text-gray-400">{r.lastLogin?r.lastLogin.toLocaleDateString():'Never'}</td><td><div className="font-semibold text-white">{r.renewal?.renewalDate?r.renewal.renewalDate.toLocaleDateString():'Not set'}</div><span className={`text-xs ${renewalTone(r.renewalDays,r.renewal?.renewalStatus??'NOT_SET')==='red'?'text-red-300':renewalTone(r.renewalDays,r.renewal?.renewalStatus??'NOT_SET')==='amber'?'text-amber-300':'text-gray-500'}`}>{renewalText(r.renewalDays)}</span></td><td><RenewalStatus value={r.renewal?.renewalStatus??'NOT_SET'}/></td></tr>)}</tbody></table></div></section>

  <div className="grid gap-5 xl:grid-cols-3"><section className="rounded-2xl border border-teal/20 bg-gray-800/40 p-5 xl:col-span-2"><div className="flex items-center gap-2 text-teal"><CalendarClock size={18}/><h2 className="font-extrabold text-white">Renewal Control Center</h2></div><p className="mt-1 text-xs text-gray-500">Set the contractual renewal date, owner and current renewal motion for each customer.</p><div className="mt-5 space-y-3">{rows.map(r=><details key={r.o.id} className="rounded-xl border border-gray-700 bg-gray-900/30"><summary className="cursor-pointer list-none p-4"><div className="flex items-center justify-between gap-4"><div><div className="font-bold text-white">{r.o.name}</div><div className="mt-1 text-xs text-gray-500">{r.renewal?.renewalDate?`${r.renewal.renewalDate.toLocaleDateString()} · ${renewalText(r.renewalDays)}`:'Renewal date not set'}</div></div><RenewalStatus value={r.renewal?.renewalStatus??'NOT_SET'}/></div></summary><form action={saveCustomerRenewalAction} className="grid gap-3 border-t border-gray-700 p-4 md:grid-cols-2"><input type="hidden" name="organizationId" value={r.o.id}/><label className="text-xs font-bold text-gray-400">Renewal date<input type="date" name="renewalDate" defaultValue={r.renewal?.renewalDate?r.renewal.renewalDate.toISOString().slice(0,10):''} className="mt-1 w-full rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-white"/></label><label className="text-xs font-bold text-gray-400">Renewal owner<input name="renewalOwner" defaultValue={r.renewal?.renewalOwner??''} placeholder="Owner name" className="mt-1 w-full rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-white"/></label><label className="text-xs font-bold text-gray-400">Renewal status<select name="renewalStatus" defaultValue={r.renewal?.renewalStatus??'PLANNING'} className="mt-1 w-full rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-white"><option value="PLANNING">Planning</option><option value="IN_PROGRESS">In Progress</option><option value="COMMITTED">Committed</option><option value="RENEWED">Renewed</option><option value="AT_RISK">At Risk</option><option value="NOT_SET">Not Set</option></select></label><label className="text-xs font-bold text-gray-400 md:col-span-2">Renewal notes<textarea name="renewalNotes" defaultValue={r.renewal?.renewalNotes??''} rows={2} placeholder="Decision process, risks, next steps..." className="mt-1 w-full rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-white"/></label><div className="md:col-span-2"><button className="rounded-lg bg-evergreen px-4 py-2.5 text-sm font-bold text-white">Save Renewal Details</button></div></form></details>)}</div></section>
  <section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><div className="flex items-center gap-2 text-amber-300"><AlertTriangle size={18}/><h2 className="font-extrabold">Upcoming Renewals</h2></div><p className="mt-1 text-xs text-gray-500">Next 120 days.</p><div className="mt-4 space-y-2">{upcoming.slice(0,10).map(r=><div key={r.o.id} className="rounded-xl border border-gray-700 bg-gray-900/30 p-3"><div className="flex justify-between gap-3"><div><div className="font-bold text-white">{r.o.name}</div><div className="mt-1 text-xs text-gray-500">{r.renewal?.renewalDate?.toLocaleDateString()} · {r.renewal?.renewalOwner||'No owner'}</div></div><span className="text-xs font-bold text-amber-300">{renewalText(r.renewalDays)}</span></div></div>)}{upcoming.length===0&&<p className="text-sm text-gray-400">No renewals currently fall within the next 120 days.</p>}</div></section></div>

  <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5"><div className="flex items-center gap-2 text-amber-300"><AlertTriangle size={18}/><h2 className="font-extrabold">Customer Attention Queue</h2></div><div className="mt-4 space-y-2">{rows.filter(r=>r.health.label!=='Healthy'||r.renewal?.renewalStatus==='AT_RISK').slice(0,8).map(r=><Link key={r.o.id} href={`/admin/organizations/${r.o.id}`} className="flex justify-between rounded-xl border border-gray-700 bg-gray-900/30 p-3"><div><div className="font-bold text-white">{r.o.name}</div><div className="text-xs text-gray-500">{r.renewal?.renewalStatus==='AT_RISK'?'Renewal at risk':`${r.health.label} · ${r.lastLogin?`${daysSince(r.lastLogin)} days since login`:'No customer login yet'}`}</div></div><span className="text-xs font-bold text-amber-300">Review →</span></Link>)}</div></section>
  <section className="rounded-2xl border border-gray-800 bg-gray-800/40 p-5"><div className="flex items-center gap-2 text-teal"><CalendarClock size={18}/><h2 className="font-extrabold text-white">Lifecycle Controls</h2></div><div className="mt-4 space-y-3"><Link href="/admin/orders" className="block rounded-xl border border-gray-700 p-4"><b className="text-white">Fulfillment & Onboarding</b><p className="mt-1 text-xs text-gray-500">Manage signed orders, provisioning, activation and launch.</p></Link><Link href="/admin" className="block rounded-xl border border-gray-700 p-4"><b className="text-white">Platform Command Center</b><p className="mt-1 text-xs text-gray-500">Return to customer, platform and operating metrics.</p></Link></div></section></div></div>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number|string}){return <div className="rounded-2xl border border-gray-800 bg-gray-800/40 p-4"><div className="flex items-center gap-2 text-teal">{icon}<span className="text-xs font-bold uppercase text-gray-500">{label}</span></div><div className="mt-3 text-2xl font-black text-white">{value}</div></div>}
function Health({label,tone}:{label:string;tone:string}){const c=tone==='green'?'bg-emerald-500/10 text-emerald-300':tone==='red'?'bg-red-500/10 text-red-300':'bg-amber-500/10 text-amber-300';return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${c}`}>{label}</span>}
function RenewalStatus({value}:{value:string}){const c=value==='RENEWED'||value==='COMMITTED'?'bg-emerald-500/10 text-emerald-300':value==='AT_RISK'?'bg-red-500/10 text-red-300':value==='IN_PROGRESS'||value==='PLANNING'?'bg-amber-500/10 text-amber-300':'bg-gray-700 text-gray-400';return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${c}`}>{value.replaceAll('_',' ')}</span>}
